#! /bin/bash

rm -rf target && mkdir -p target/classes

CP=`lein classpath`
find src/java -name "*.java" | xargs javac -cp $CP -d target/classes -sourcepath src/java/

if [ $# -gt 0 ]; then
    # lein test needs this
    echo "compile java test code"
    find test/java -name "*.java" | xargs javac -cp $CP -d target/classes -sourcepath test/java
fi
