#!/bin/bash

./scripts/javac with-test

CP=`lein classpath`

java -cp "$CP" \
    -Xms128m -Xmx128m \
    -Xdebug -Xrunjdwp:transport=dt_socket,address=9094,server=y,suspend=n \
    clojure.main -m org.httpkit.ssl-bench
