#!/bin/bash

./scripts/javac with-test

CP=`lein classpath`

REQUEST_N=150000
REQUEST_C=100

# -Xdebug -Xrunjdwp:transport=dt_socket,address=9093,server=y,suspend=n \

java -cp "$CP" \
    clojure.main -m org.httpkit.benchmark -p 8000

exit 0

PID=$!
echo "pid is $PID, sleep 4 seconds to wait start, listen on port 8000"
sleep 4
echo "warm up JVM by ab -n $REQUEST_N -c $REQUEST_C"
ab -n $REQUEST_N -c $REQUEST_C http://localhost:8000/
