name: Graal tests
on: [push, pull_request]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        java: ['17', '21', '25']
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1.6.3
        with:
          java-version: ${{ matrix.java }}
          distribution: graalvm-community
          components: native-image
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeLaGuardo/setup-clojure@13.6.0
        with:
          lein: 2.12.0
          bb: latest

      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: deps-${{ runner.os }}-${{ hashFiles('project.clj') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Run Graal tests
        run: bb run-graal-tests
        working-directory: test-graal
