name: Graal tests
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        java: ['25']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: DeLaGuardo/setup-clojure@13.6
        with:
          lein: latest
          bb: latest

      - uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: deps-${{ hashFiles('deps.edn') }}
          restore-keys: deps-

      - name: Run Graal tests
        run: bb run-graal-tests
        working-directory: test-graal
